openapi: 3.2.0
info:
  title: Songtradr Allowed Values API
  description: This is the Songtradr API.
  contact:
    name: Songtradr Inc.
    url: https://songtradr.com
    email: info@songtradr.com
  version: 3.0.0
servers:
- url: https://api.songtradr.com
  description: Generated server url
tags:
- name: allowed-values
paths:
  /api/v1/allowedValues/musicalFeatures:
    get:
      tags:
      - allowed-values
      summary: Allowed values for music descriptive parameters to be used in the searchAll…
      operationId: allowedMusicalFeatures
      parameters:
      - name: responseSize
        in: query
        description: Size the response should have. Deprecated because there is no difference in the response size starting with taxonomyVersion v2.4
        required: false
        deprecated: true
        schema:
          type: string
          default: s
          enum:
          - s
          - l
      - name: taxonomyVersion
        in: query
        description: The version of the AI taxonomy to use.
        required: false
        schema:
          type: string
          default: v2_4
          enum:
          - v2_4
        example: v2_4
      responses:
        '200':
          description: Retrieved searchFilters
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SearchFilterValuesDTO'
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
                example:
                  $ref: '#/components/examples/'
              example:
                timestamp: '2026-05-15T13:32:42.291+00:00'
                status: 401
                error: Unauthorized
                message: a detailed error message
                path: /api/v1/allowedValues/musicalFeatures
        '429':
          description: Too Many Requests
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
                example:
                  $ref: '#/components/examples/'
              example:
                timestamp: '2026-05-15T13:32:42.291+00:00'
                status: 429
                error: Too Many Requests
                message: a detailed error message
                path: /api/v1/allowedValues/musicalFeatures
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
                example:
                  $ref: '#/components/examples/'
              example:
                timestamp: '2026-05-15T13:32:42.291+00:00'
                status: 500
                error: Internal Server Error
                message: a detailed error message
                path: /api/v1/allowedValues/musicalFeatures
components:
  schemas:
    ErrorResponse:
      description: Bearer token to be used for authentication.
      properties:
        timestamp:
          type: string
          format: date-time
          description: timestamp
        status:
          type: integer
          format: int32
          description: HTTP Status code
        error:
          type: string
          description: HTTP status message
        message:
          type: string
          description: detailed error message
        path:
          type: string
          description: path of the called API endpoint
      required:
      - error
      - status
      - timestamp
    SearchFilterValuesDTO:
      type: object
      description: Categories of musical features that can be used as search filters.
      properties:
        primaryMoodCluster:
          type: array
          items:
            type: string
        secondaryMoodCluster:
          type: array
          items:
            type: string
        tertiaryMoodCluster:
          type: array
          items:
            type: string
        valence:
          type: array
          items:
            type: string
        arousal:
          type: array
          items:
            type: string
        pleasantness:
          type: array
          items:
            type: string
        engagement:
          type: array
          items:
            type: string
        vocals:
          type: array
          items:
            type: string
        dominantInstrument:
          type: array
          items:
            type: string
        secondaryInstrument:
          type: array
          items:
            type: string
        tertiaryInstrument:
          type: array
          items:
            type: string
        energy:
          type: array
          items:
            type: string
        soundGeneration:
          type: array
          items:
            type: string
        tempo:
          type: array
          items:
            type: string
        scale:
          type: array
          items:
            type: string
        key:
          type: array
          items:
            type: string
        rhythm:
          type: array
          items:
            type: string
        primarySoundCharacter:
          type: array
          items:
            type: string
        timbre:
          type: array
          items:
            type: string
        roughness:
          type: array
          items:
            type: string
        tonality:
          type: array
          items:
            type: string
        harmony:
          type: array
          items:
            type: string
        texture:
          type: array
          items:
            type: string
        groovyness:
          type: array
          items:
            type: string
        grooviness:
          type: array
          items:
            type: string
        space:
          type: array
          items:
            type: string
        loudness:
          type: array
          items:
            type: string
        productionRating:
          type: array
          items:
            type: string
        performanceRating:
          type: array
          items:
            type: string
        songRating:
          type: array
          items:
            type: string
        audienceAge:
          type: array
          items:
            type: string
        secondaryAudienceAge:
          type: array
          items:
            type: string
        tertiaryAudienceAge:
          type: array
          items:
            type: string
        audienceGender:
          type: array
          items:
            type: string
        audienceRegion:
          type: array
          items:
            type: string
        secondaryAudienceRegion:
          type: array
          items:
            type: string
        tertiaryAudienceRegion:
          type: array
          items:
            type: string
        originDecade:
          type: array
          items:
            type: string
        originRegion:
          type: array
          items:
            type: string
        languageOfPerformance:
          type: array
          items:
            type: string
        curateability:
          type: array
          items:
            type: string
        useCase:
          type: array
          items:
            type: string
        channelSuitability:
          type: array
          items:
            type: string
        pretzelStationSuitability:
          type: array
          items:
            type: string
        recordingEnvironment:
          type: array
          items:
            type: string
        content:
          type: array
          items:
            type: string
        moodPlayer:
          type: array
          items:
            type: string
        secondaryMoodPlayer:
          type: array
          items:
            type: string
        brandAttributes:
          type: array
          items:
            type: string
      required:
      - arousal
      - audienceAge
      - audienceGender
      - audienceRegion
      - brandAttributes
      - channelSuitability
      - content
      - curateability
      - dominantInstrument
      - energy
      - engagement
      - grooviness
      - groovyness
      - harmony
      - key
      - languageOfPerformance
      - loudness
      - moodPlayer
      - originDecade
      - originRegion
      - performanceRating
      - pleasantness
      - pretzelStationSuitability
      - primaryMoodCluster
      - primarySoundCharacter
      - productionRating
      - recordingEnvironment
      - rhythm
      - roughness
      - scale
      - secondaryAudienceAge
      - secondaryAudienceRegion
      - secondaryInstrument
      - secondaryMoodCluster
      - secondaryMoodPlayer
      - songRating
      - soundGeneration
      - space
      - tempo
      - tertiaryAudienceAge
      - tertiaryAudienceRegion
      - tertiaryInstrument
      - tertiaryMoodCluster
      - texture
      - timbre
      - tonality
      - useCase
      - valence
      - vocals
  securitySchemes:
    bearer-jwt:
      type: http
      description: "To authenticate, you have to call POST https://api.songtradr.com/api/v1/user/login \nand use the response's jwtToken as a bearer Token in all following API calls."
      name: Authorization
      in: header
      scheme: bearer
      bearerFormat: JWT
